doctrine:
    orm:
        mappings:
            Annotation:
                type: 'annotation'
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Annotation'
                prefix: 'DoctrineEncryptBundle\Demo\Symfony54\Entity\Annotation'
                alias: DoctrineEncryptBundle\Demo\Symfony54
            Attributes:
                type: 'attribute'
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Attribute'
                prefix: 'DoctrineEncryptBundle\Demo\Symfony54\Entity\Attribute'
                alias: DoctrineEncryptBundle\Demo\Symfony54

