controllers:
    resource:
        path:      ../../src/Controller/
        namespace: DoctrineEncryptBundle\Demo\Symfony7x\Controller
    type: attribute

kernel:
    resource: DoctrineEncryptBundle\Demo\Symfony7x\Kernel
    type: attribute
