services:
  ambta_doctrine_encrypt.encryptor:
    class: "%ambta_doctrine_encrypt.encryptor_class_name%"
    arguments:
      - '@=service("ambta_doctrine_encrypt.secret_factory").getSecret()'

  ambta_doctrine_encrypt.secret_factory:
    class: Ambta\DoctrineEncryptBundle\Factories\SecretFactory
    arguments:
      $encryptor:            '%ambta_doctrine_encrypt.encryptor_class_name%'
      $secretDirectory:      '%ambta_doctrine_encrypt.secret_directory_path%'
      $enableSecretCreation: '%ambta_doctrine_encrypt.enable_secret_generation%'