doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        report_fields_where_declared: true
        mappings:
            Annotation:
                type: 'annotation'
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Annotation'
                prefix: 'DoctrineEncryptBundle\Demo\Symfony6x\Entity\Annotation'
                alias: DoctrineEncryptBundle\Demo\Symfony6x
            Attributes:
                type: 'attribute'
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity/Attribute'
                prefix: 'DoctrineEncryptBundle\Demo\Symfony6x\Entity\Attribute'
                alias: DoctrineEncryptBundle\Demo\Symfony6x

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
